# This workflow will install Python dependencies and run tests for every push and pull request.
# It tests against a matrix of Python and NumPy versions.

name: Python package CI

on:
  push:
    branches:
      - '**' # This triggers the workflow on a push to ANY branch
  pull_request:
    branches: [ master ] # Trigger on pull requests targeting master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Allows all jobs to run even if one fails
      matrix:
        python-version: [ "3.9", "3.12" ]
        # Test against a specific version from the 1.2x series and the latest version.
        numpy-version: [ "1.26.4", "latest" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        # Pinning to a specific, recent version of the action to avoid future breaking changes.
        uses: snok/install-poetry@v1.4.0

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies with specific NumPy version
        run: |
          if [ "${{ matrix.numpy-version }}" = "latest" ]; then
            echo "Installing dependencies with the latest version of NumPy..."
            # Let poetry resolve the latest compatible version
            poetry install --with dev
          else
            echo "Installing dependencies with NumPy version ${{ matrix.numpy-version }}..."
            # Use 'poetry add' to cleanly override the version for this CI run
            poetry add "numpy==${{ matrix.numpy-version }}"
            poetry install --with dev
          fi

      - name: Show installed packages
        run: poetry show

      - name: Run tests
        run: poetry run pytest
